on:
  push:
    branches:
      - nightly

permissions:
  contents: write
  packages: write

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: cd ./web && npm i && npm run build
      - run: cd ..
      - name: Setup Go '1.21.x'
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
          cache-dependency-path: ./go.sum
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version
      - name: Run make check
        run: make check

  release-docker:
    name: Release Docker Image
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.1.1
        with:
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/usenet-drive:nightly
